apiVersion: v1
kind: Pod
metadata:
  name: ollama
spec:
  initContainers:
  - name: preload-model
    image: ollama/ollama:latest
    command: ["sh", "-c"]
    args:
      - |
        ollama serve &
        sleep 5
        ollama pull llama3
    volumeMounts:
    - name: ollama-storage
      mountPath: /root/.ollama

  containers:
  - name: ollama
    image: ollama/ollama:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 11434
    volumeMounts:
    - name: ollama-storage
      mountPath: /root/.ollama
    command: ["ollama"]
    args: ["serve"]

  volumes:
  - name: ollama-storage
    persistentVolumeClaim:
      claimName: ollama-pvc-2