apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/ollama-models
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc-2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
